version: "3.9"

services:
  mongo:
    image: mongo:7.0             # Use the latest stable version
    container_name: sonali_mongo
    ports:
      - "27017:27017"            # Map host port to container
    environment:
      MONGO_INITDB_DATABASE: sonali_mongo
      MONGO_INITDB_ROOT_USERNAME: admin  # optional root user
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo_data:/data/db      # persist data on host
    restart: unless-stopped

volumes:
  mongo_data:
